<!Doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta name="referrer" content="always" />
    <meta name="description" content="">
    <title>SaySomeThing</title>

    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="icon" sizes="any" mask href="//www.baidu.com/img/baidu.svg">

    <meta name="keywords" content="心里 心里词语信息 心里释义 心里出处 心里心里与心理">
    <meta name="image" content="https://bkssl.bdimg.com/cms/static/baike.png">
</head>
<body>
    eeeeee

    <?php echo $name; ?>
</body>
</html>